version: "3.8"
services:
  picture-generation:
    build:
      context: .
    # Uncomment and edit below if you want to expose ports or add volumes
    # ports:
    #   - "5002:5002"
    # volumes:
    #   - ./somefolder:/app/somefolder