services:
  picture-generation:
    build:
      context: .
    # networks:
    #   - my_network
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

# networks:
#   my_network:
#     driver: bridge