services:
  main_app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - picture-generation
    networks:
      - my_network

  picture-generation:
    build: ../pictureGeneration
    ports:
      - "5002:5002"
    networks:
      - my_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


networks:
  my_network:
    driver: bridge
